CONFIG_GPIO=y
CONFIG_LOG=y
CONFIG_LOG_THREAD_ID_PREFIX=y
CONFIG_LOG_BACKEND_UART_ASYNC=y
CONFIG_TRACING=y

CONFIG_UART_ASYNC_API=y

#USE IN GDB: 
#dump binary value build/trace.bin *RecorderDataPtr
CONFIG_PERCEPIO_TRACERECORDER=y
CONFIG_PERCEPIO_TRC_CFG_STREAM_PORT_RINGBUFFER=y
CONFIG_PERCEPIO_TRC_CFG_STREAM_PORT_RINGBUFFER_SIZE=65536