# CONFIG_DEBUG=y
# CONFIG_DEBUG_OPTIMIZATIONS=y
# CONFIG_KERNEL_LOG_LEVEL_DBG=y

CONFIG_GPIO=y
CONFIG_LOG=y
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=2048
# CONFIG_LOG_THREAD_ID_PREFIX=y
CONFIG_LOG_BACKEND_UART=y
# CONFIG_LOG_BACKEND_UART_ASYNC=y
CONFIG_LOG_CMDS=y

# CONFIG_UART_ASYNC_API=y

CONFIG_SHELL=y
CONFIG_SHELL_LOG_BACKEND=n
CONFIG_UART_SHELL=y

# command used in GDB to store trace data: 
# dump binary value build/trace.bin *RecorderDataPtr
# CONFIG_TRACING=y
# CONFIG_PERCEPIO_TRACERECORDER=y
# CONFIG_PERCEPIO_TRC_CFG_CTRL_TASK_STACK_SIZE=1048
# CONFIG_PERCEPIO_TRC_CFG_STREAM_PORT_RINGBUFFER=y
# CONFIG_PERCEPIO_TRC_CFG_STREAM_PORT_RINGBUFFER_SIZE=32768

# Copy form zephyr/samples/subsys/display/lvgl/prj.conf start
CONFIG_LV_Z_MEM_POOL_SIZE=16384
# CONFIG_LV_Z_SHELL=y
CONFIG_MAIN_STACK_SIZE=4096

CONFIG_DISPLAY=y
CONFIG_DISPLAY_LOG_LEVEL_ERR=y


CONFIG_LVGL=y
CONFIG_LV_USE_LOG=y
CONFIG_LV_USE_LABEL=y
CONFIG_LV_USE_ARC=y
CONFIG_LV_USE_MONKEY=y
CONFIG_LV_FONT_MONTSERRAT_14=y
# Copy from zephyr/samples/subsys/display/lvgl/prj.conf end
# CONFIG_LV_LOG_LEVEL_TRACE=y

CONFIG_LV_COLOR_DEPTH_1=y
CONFIG_LV_Z_VDB_SIZE=64
CONFIG_LV_Z_BITS_PER_PIXEL=1
CONFIG_LV_USE_THEME_MONO=y
CONFIG_LV_DPI_DEF=148
CONFIG_LV_Z_COLOR_MONO_HW_INVERSION=y

# CONFIG_INSTRUMENTATION=y
# CONFIG_INSTRUMENTATION_MODE_CALLGRAPH_TRACE_BUFFER_SIZE=16384
# CONFIG_INSTRUMENTATION_MODE_CALLGRAPH=y    # For tracing
# CONFIG_INSTRUMENTATION_MODE_STATISTICAL=y  # For profiling

CONFIG_LOG_PRINTK=n